### ISSUE TITLE
Know how to implement any algorithm in Rust?

### ISSUE THREAD

**Issue by abranhe** [AllAlgorithms/rust#4]
<p align="center">
  <img src="https://cdn.abranhe.com/projects/algorithms/algorithms.svg">
</p>

Hi, everyone! 

> Do you know any algorithm implementation in any language, that you wanna share with us?

Open a pull request in any of the programming languages available, or in [Rust](https://github.com/AllAlgorithms/rust) this case

**Comment by TheBestTvarynka** [comment]
I would like to write a Queue, Stack, Tree, and other data structures. Can I take this? I browsed repository files and it seems like this data structures is not implemented.

**Comment by TheBestTvarynka** [comment]
Hi, can you make a review of my PR's (or approve them :smile: )? If you find any mistake, I'll fix it.

**Comment by TheBestTvarynka** [comment]
Are you still open to new pull requests?)
